### PR TITLE
132 [front] limit website upload

### PR DESCRIPTION
**Pull request by SebastienValla**
A limit of 1.5MB should be applied onto the uploaded website.

    Display error message if file is too big
    Disable upload button if file is too big

### CODE REVIEW

**Review by Thykof — APPROVED** [review]
not so easy to read with the code formatting, it would be easier if there were 2 commits: one for changes and one for code formating; but it is ok for me.

**Review by ASAPSegfault — APPROVED** [review]
We must do something about code formatting but otherwise I don't see anything to change in the logic

**Comment by Thykof** [comment]
@SebastienValla what are the rules you used for prettier to format the code?

**Comment by gregLibert** [comment]
@SebastienValla can you solve the conflicts ?

**Comment by SebastienValla** [comment]
> 
Done

**Pull request merged**
