### PR TITLE
CI: fix CI and factorize install

### PR DESCRIPTION
**Pull request by peterjah**

### CODE REVIEW

**Review by thomas-senechal — APPROVED** [review]
Very good improvements !

**Review by Thykof — COMMENTED** [review]
Great! is it possible to factor build job to avoid duplicate code between build and release worflows

**Comment by peterjah** [comment]
> Great! is it possible to factor build job to avoid duplicate code between build and release worflows

Of crouse sir !! Lets do it

**Review by Thykof — APPROVED** [review]
awesome!

**Pull request merged**
