### PR TITLE
lints all files

### PR DESCRIPTION
**Pull request by gregLibert**

### CODE REVIEW

**Comment by gregLibert** [comment]
@Trottoir I do know that review so much files is painful...
@SlnPons if you can test it :-)

**Comment by SlnPons** [comment]
Probably lack of knowledge about GitHub, but I don't get which messages we're talking about here. Could you help? 
After that, happy to test.

**Comment by SlnPons** [comment]
@gregLibert I tested the branch and was blocked to create the SC for the DNS name. 
To reproduce: 
- run Thyra
- go to my.massa/thyra/wallet
- Create a wallet
- Go to the 'websites' page
- Type a website name
- click on create SC
- enter password in the pop-up
BLOCKED HERE
See error in the terminal and console attached
image

image

**Review by Trottoir — COMMENTED** [review]
REVIEWED
If I understand well, We need to `fmtError` with a dedicated message on each error we are returning.

**Comment by gregLibert** [comment]
@SlnPons @Trottoir can we close it ?

**Comment by SlnPons** [comment]
@gregLibert Test successfully passed. Ok on my side.

**Pull request merged**
