### PR TITLE
Update wallet url

### PR DESCRIPTION
**Pull request by Thykof**
This PR update the wallet url following the API refacto: /api/accounts.

We will merge this PR after the next release of the wallet will be published

### CODE REVIEW

**Comment by Thykof** [comment]
I have not tested yet.

**Comment by SlnPons** [comment]
@Thykof the CI is red here. Can this still be code-review?

**Comment by SlnPons** [comment]
Hey @Thykof I'm a bit lost so sorry if I ask (again) this question, what are the next steps with this ticket please? 
As no one is assigned but it's in progress, I'm keen to understand so I can help closing it when you're not here :)

**Comment by Thykof** [comment]
CI job test-api-robot is failing because it installs v0.0.12 of wallet plugin. This branch is made to work with the next release, v0.1.0. To make the CI work:
- publish v0.1.0 of the wallet plugin,
- merge #725,
- rebase this branch onto main,
- change the robot test to install v0.1.0 of the wallet plugin,
- see if the CI passes,
- merge this PR,
- release MassaStation.

**Comment by SlnPons** [comment]
- publish v0.1.0 of the wallet plugin - done: https://github.com/massalabs/thyra-plugin-wallet/releases/tag/v0.1.0
- merge https://github.com/massalabs/thyra/pull/725 - done
- rebase this branch onto main,
- change the robot test to install v0.1.0 of the wallet plugin,
- see if the CI passes,
- merge this PR,
- release MassaStation.

**Review by peterjah — APPROVED** [review]

**Pull request merged**
