### PR TITLE
added update call to the postman partition

### PR DESCRIPTION
**Pull request by Pierregvx**

### CODE REVIEW

**Comment by Thykof** [comment]
probably out of scope, but I got 


```json
{
    "code": 400,
    "message": "parsing body body from \"\" failed, because json: cannot unmarshal number into Go struct field PluginManagerRegisterBody.id of type string"
}
```

on `http://my.massa:{{port}}/plugin-manager/register`

**Comment by Thykof** [comment]
again, probably out of scope, but I got 

```json
{
    "code": "Plugin-0001",
    "message": "Error: running plugin /Users/nathanmassa/.config/thyra/plugins/thyra-plugin-hello-world/thyra-plugin-hello-world after installation: creating plugin: start plugin thyra-plugin-hello-world: starting command: fork/exec /Users/nathanmassa/.config/thyra/plugins/thyra-plugin-hello-world/thyra-plugin-hello-world: exec format error"
}
```

on `http://my.massa:{{port}}/plugin-manager?source={{pluginSource}}`

**Comment by Pierregvx** [comment]
> again, probably out of scope, but I got
> 
> ```json
> {
>     "code": "Plugin-0001",
>     "message": "Error: running plugin /Users/nathanmassa/.config/thyra/plugins/thyra-plugin-hello-world/thyra-plugin-hello-world after installation: creating plugin: start plugin thyra-plugin-hello-world: starting command: fork/exec /Users/nathanmassa/.config/thyra/plugins/thyra-plugin-hello-world/thyra-plugin-hello-world: exec format error"
> }
> ```
> 
> on `http://my.massa:{{port}}/plugin-manager?source={{pluginSource}}`

I didn't get this, the install worked for me

**Comment by Thykof** [comment]
> > again, probably out of scope, but I got
> > ```json
> > {
> >     "code": "Plugin-0001",
> >     "message": "Error: running plugin /Users/nathanmassa/.config/thyra/plugins/thyra-plugin-hello-world/thyra-plugin-hello-world after installation: creating plugin: start plugin thyra-plugin-hello-world: starting command: fork/exec /Users/nathanmassa/.config/thyra/plugins/thyra-plugin-hello-world/thyra-plugin-hello-world: exec format error"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > on `http://my.massa:{{port}}/plugin-manager?source={{pluginSource}}`
> 
> I didn't get this, the install worked for me

yes that probably because I haven't migrated my certs after #657

**Review by peterjah — APPROVED** [review]

**Pull request merged**
